# ASP.NET Core
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    verbosityRestore: 'Minimal'
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# trigger:
- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: 'drop'
# - master

# pool:
#   vmImage: 'Ubuntu-16.04'

# variables:
#   buildConfiguration: 'Release'

# steps:
# - task: DotNetCoreCLI@2
#   displayName: 'dotnet restore'
#   inputs:
#     command: restore
# - task: DotNetCoreCLI@2
#   displayName: 'dotnet publish'
#   inputs:
#     command: publish

#     publishWebProjects: false 

#     arguments: '--output $(build.artifactstagingdirectory) -c Release'

#     modifyOutputPath: false

#     workingDirectory: '$(System.DefaultWorkingDirectory)/'
# - task: PublishBuildArtifacts@1
#   displayName: 'Publish Artifact: drop'