// <auto-generated />
using System;
using Bidding.Database.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bidding.Migrations
{
    [DbContext(typeof(BiddingContext))]
    [Migration("20190714164338_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bidding.Database.DatabaseModels.Auctions.Auction", b =>
                {
                    b.Property<int>("AuctionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ApplyTillDate");

                    b.Property<int>("AuctionCategoryId");

                    b.Property<int>("AuctionFormatId");

                    b.Property<int>("AuctionStatusId");

                    b.Property<int>("AuctionTypeId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("CreatedBy");

                    b.Property<bool>("Deleted");

                    b.Property<DateTime>("EndDate");

                    b.Property<DateTime>("LastUpdatedAt");

                    b.Property<int>("LastUpdatedBy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime?>("StartDate");

                    b.Property<int>("StartingPrice");

                    b.HasKey("AuctionId");

                    b.HasIndex("AuctionCategoryId");

                    b.HasIndex("AuctionFormatId");

                    b.HasIndex("AuctionStatusId");

                    b.HasIndex("AuctionTypeId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Auctions");
                });

            modelBuilder.Entity("Bidding.Database.DatabaseModels.Auctions.AuctionCondition", b =>
                {
                    b.Property<int>("AuctionConditionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("CreatedBy");

                    b.Property<bool>("Deleted");

                    b.Property<DateTime>("LastUpdatedAt");

                    b.Property<int>("LastUpdatedBy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("AuctionConditionId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("AuctionConditions");

                    b.HasData(
                        new
                        {
                            AuctionConditionId = 1,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Lietota"
                        },
                        new
                        {
                            AuctionConditionId = 2,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Jauna"
                        },
                        new
                        {
                            AuctionConditionId = 3,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Apdzīvots"
                        },
                        new
                        {
                            AuctionConditionId = 4,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Neapdzīvots"
                        },
                        new
                        {
                            AuctionConditionId = 5,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Nepieciešams remonts"
                        });
                });

            modelBuilder.Entity("Bidding.Database.DatabaseModels.Auctions.AuctionCreator", b =>
                {
                    b.Property<int>("AuctionCreatorId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactAddress")
                        .IsRequired();

                    b.Property<string>("ContactEmail")
                        .IsRequired();

                    b.Property<string>("ContactPhone")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("CreatedBy");

                    b.Property<bool>("Deleted");

                    b.Property<DateTime>("LastUpdatedAt");

                    b.Property<int>("LastUpdatedBy");

                    b.Property<int>("UserId");

                    b.HasKey("AuctionCreatorId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("AuctionCreators");
                });

            modelBuilder.Entity("Bidding.Database.DatabaseModels.Auctions.AuctionDetails", b =>
                {
                    b.Property<int>("AuctionDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<int>("AuctionItemId");

                    b.Property<string>("Axis");

                    b.Property<int?>("CadastreNumber");

                    b.Property<int?>("ConditionId");

                    b.Property<string>("Coordinates");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("CreatedBy");

                    b.Property<bool>("Deleted");

                    b.Property<string>("EngineSize");

                    b.Property<string>("Evaluation");

                    b.Property<int?>("FloorCount");

                    b.Property<int?>("FuelTypeId");

                    b.Property<string>("IdentificationNumber")
                        .HasMaxLength(50);

                    b.Property<bool?>("InspectionActive");

                    b.Property<DateTime>("LastUpdatedAt");

                    b.Property<int>("LastUpdatedBy");

                    b.Property<string>("Make");

                    b.Property<int?>("ManufacturingYear");

                    b.Property<int?>("MeasurementType");

                    b.Property<int?>("MeasurementValue");

                    b.Property<string>("Model");

                    b.Property<int?>("Region");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(50);

                    b.Property<int?>("RoomCount");

                    b.Property<int?>("TransmissionId");

                    b.Property<int?>("UserId");

                    b.HasKey("AuctionDetailsId");

                    b.HasIndex("AuctionItemId");

                    b.HasIndex("ConditionId");

                    b.HasIndex("FuelTypeId");

                    b.HasIndex("TransmissionId");

                    b.HasIndex("UserId");

                    b.ToTable("AuctionDetails");
                });

            modelBuilder.Entity("Bidding.Database.DatabaseModels.Auctions.AuctionFormat", b =>
                {
                    b.Property<int>("AuctionFormatId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("CreatedBy");

                    b.Property<bool>("Deleted");

                    b.Property<DateTime>("LastUpdatedAt");

                    b.Property<int>("LastUpdatedBy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("AuctionFormatId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("AuctionFormats");

                    b.HasData(
                        new
                        {
                            AuctionFormatId = 1,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Cenu aptauja"
                        },
                        new
                        {
                            AuctionFormatId = 2,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Izsole elektroniski"
                        },
                        new
                        {
                            AuctionFormatId = 3,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Izsole klātienē"
                        });
                });

            modelBuilder.Entity("Bidding.Database.DatabaseModels.Auctions.AuctionItem", b =>
                {
                    b.Property<int>("AuctionItemId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuctionId");

                    b.Property<int>("AuctionItemCategoryId");

                    b.Property<int>("AuctionItemTypeId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("CreatedBy");

                    b.Property<bool>("Deleted");

                    b.Property<DateTime>("LastUpdatedAt");

                    b.Property<int>("LastUpdatedBy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("AuctionItemId");

                    b.HasIndex("AuctionId");

                    b.HasIndex("AuctionItemCategoryId");

                    b.HasIndex("AuctionItemTypeId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("AuctionItems");
                });

            modelBuilder.Entity("Bidding.Database.DatabaseModels.Auctions.AuctionStatus", b =>
                {
                    b.Property<int>("AuctionStatusId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("CreatedBy");

                    b.Property<bool>("Deleted");

                    b.Property<DateTime>("LastUpdatedAt");

                    b.Property<int>("LastUpdatedBy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("AuctionStatusId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("AuctionStatuses");

                    b.HasData(
                        new
                        {
                            AuctionStatusId = 1,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Aktīva"
                        },
                        new
                        {
                            AuctionStatusId = 2,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Pārtraukta"
                        },
                        new
                        {
                            AuctionStatusId = 3,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Beigusies"
                        });
                });

            modelBuilder.Entity("Bidding.Database.DatabaseModels.Item.ItemCondition", b =>
                {
                    b.Property<int>("ItemConditionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("CreatedBy");

                    b.Property<bool>("Deleted");

                    b.Property<DateTime>("LastUpdatedAt");

                    b.Property<int>("LastUpdatedBy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ItemConditionId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("ItemConditions");

                    b.HasData(
                        new
                        {
                            ItemConditionId = 1,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Jauns"
                        },
                        new
                        {
                            ItemConditionId = 2,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Lietots"
                        });
                });

            modelBuilder.Entity("Bidding.Database.DatabaseModels.Users.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("CreatedBy");

                    b.Property<bool>("Deleted");

                    b.Property<DateTime>("LastUpdatedAt");

                    b.Property<int>("LastUpdatedBy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("UserId");

                    b.HasKey("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "User"
                        },
                        new
                        {
                            RoleId = 2,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("Bidding.Database.DatabaseModels.Users.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("CreatedBy");

                    b.Property<bool>("Deleted");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .HasMaxLength(50);

                    b.Property<DateTime>("LastUpdatedAt");

                    b.Property<int>("LastUpdatedBy");

                    b.Property<string>("LoginEmail")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50);

                    b.Property<int>("RoleId");

                    b.Property<string>("UniqueIdentifier")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            FirstName = "Test",
                            LastName = "Admin",
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            LoginEmail = "dummyadmin@bidding.lv",
                            MiddleName = "",
                            RoleId = 2,
                            UniqueIdentifier = ""
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            FirstName = "Test",
                            LastName = "User",
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            LoginEmail = "dummyuser@bidding.lv",
                            MiddleName = "",
                            RoleId = 1,
                            UniqueIdentifier = ""
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            FirstName = "Zane",
                            LastName = "",
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            LoginEmail = "zanehaartman@gmail.com",
                            MiddleName = "",
                            RoleId = 2,
                            UniqueIdentifier = ""
                        },
                        new
                        {
                            UserId = 4,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            FirstName = "Kristaps",
                            LastName = "",
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            LoginEmail = "kristaps.kerpe@gmail.com",
                            MiddleName = "",
                            RoleId = 2,
                            UniqueIdentifier = ""
                        },
                        new
                        {
                            UserId = 5,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            FirstName = "Jānis",
                            LastName = "J",
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            LoginEmail = "j.jaunozols@gmail.com",
                            MiddleName = "",
                            RoleId = 2,
                            UniqueIdentifier = ""
                        },
                        new
                        {
                            UserId = 6,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            FirstName = "Jānis",
                            LastName = "B",
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            LoginEmail = "janis.rihards.blazevics@gmail.com",
                            MiddleName = "R",
                            RoleId = 2,
                            UniqueIdentifier = ""
                        });
                });

            modelBuilder.Entity("Bidding.Database.DatabaseModels.Vehicle.VehicleFuelType", b =>
                {
                    b.Property<int>("VehicleFuelTypeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("CreatedBy");

                    b.Property<bool>("Deleted");

                    b.Property<DateTime>("LastUpdatedAt");

                    b.Property<int>("LastUpdatedBy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("VehicleFuelTypeId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("VehicleFuelTypes");

                    b.HasData(
                        new
                        {
                            VehicleFuelTypeId = 1,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Benzīns"
                        },
                        new
                        {
                            VehicleFuelTypeId = 2,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Dīzelis"
                        },
                        new
                        {
                            VehicleFuelTypeId = 3,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Benzīns/Naftas gāze"
                        },
                        new
                        {
                            VehicleFuelTypeId = 4,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Elektroniskais"
                        },
                        new
                        {
                            VehicleFuelTypeId = 5,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Hibrīds"
                        });
                });

            modelBuilder.Entity("Bidding.Database.DatabaseModels.Vehicle.VehicleTransmission", b =>
                {
                    b.Property<int>("VehicleTransmissionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("CreatedBy");

                    b.Property<bool>("Deleted");

                    b.Property<DateTime>("LastUpdatedAt");

                    b.Property<int>("LastUpdatedBy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("VehicleTransmissionId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("VehicleTransmissions");

                    b.HasData(
                        new
                        {
                            VehicleTransmissionId = 1,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Automatiskā"
                        },
                        new
                        {
                            VehicleTransmissionId = 2,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Mehāniskā"
                        });
                });

            modelBuilder.Entity("Bidding.Models.DatabaseModels.Bidding.Subscribe.Newsletter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Email")
                        .HasMaxLength(100);

                    b.Property<bool>("Estate");

                    b.Property<bool>("Items");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Phone")
                        .HasMaxLength(100);

                    b.Property<bool>("Vehicles");

                    b.HasKey("Id");

                    b.ToTable("Newsletters");
                });

            modelBuilder.Entity("Bidding.Models.DatabaseModels.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("CreatedBy");

                    b.Property<bool>("Deleted");

                    b.Property<DateTime>("LastUpdatedAt");

                    b.Property<int>("LastUpdatedBy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("CategoryId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Transports"
                        },
                        new
                        {
                            CategoryId = 2,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Manta"
                        },
                        new
                        {
                            CategoryId = 3,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Nekustamais īpašums"
                        });
                });

            modelBuilder.Entity("Bidding.Models.DatabaseModels.Type", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuctionCategoryId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("CreatedBy");

                    b.Property<bool>("Deleted");

                    b.Property<DateTime>("LastUpdatedAt");

                    b.Property<int>("LastUpdatedBy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("TypeId");

                    b.HasIndex("AuctionCategoryId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Types");

                    b.HasData(
                        new
                        {
                            TypeId = 1,
                            AuctionCategoryId = 1,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Vieglais transports līdz 3,5t"
                        },
                        new
                        {
                            TypeId = 2,
                            AuctionCategoryId = 1,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Traktortehnika"
                        },
                        new
                        {
                            TypeId = 3,
                            AuctionCategoryId = 1,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Kravas auto"
                        },
                        new
                        {
                            TypeId = 4,
                            AuctionCategoryId = 1,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Mototehnika"
                        },
                        new
                        {
                            TypeId = 5,
                            AuctionCategoryId = 1,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Piekabes"
                        },
                        new
                        {
                            TypeId = 6,
                            AuctionCategoryId = 1,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Ūdens transports"
                        },
                        new
                        {
                            TypeId = 7,
                            AuctionCategoryId = 1,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Cits transports"
                        },
                        new
                        {
                            TypeId = 8,
                            AuctionCategoryId = 2,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Biroja tehnika"
                        },
                        new
                        {
                            TypeId = 9,
                            AuctionCategoryId = 2,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Sadzīves tehnika"
                        },
                        new
                        {
                            TypeId = 10,
                            AuctionCategoryId = 2,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Instrumenti"
                        },
                        new
                        {
                            TypeId = 11,
                            AuctionCategoryId = 2,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Iekārtas"
                        },
                        new
                        {
                            TypeId = 12,
                            AuctionCategoryId = 2,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Ražošanas materiāli"
                        },
                        new
                        {
                            TypeId = 13,
                            AuctionCategoryId = 2,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Veikala produkcija"
                        },
                        new
                        {
                            TypeId = 14,
                            AuctionCategoryId = 2,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Uzņēmums"
                        },
                        new
                        {
                            TypeId = 15,
                            AuctionCategoryId = 2,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Domeins"
                        },
                        new
                        {
                            TypeId = 16,
                            AuctionCategoryId = 2,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Preču zīme"
                        },
                        new
                        {
                            TypeId = 17,
                            AuctionCategoryId = 2,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Sadzīves mēbeles"
                        },
                        new
                        {
                            TypeId = 18,
                            AuctionCategoryId = 2,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Biroja mēbeles"
                        },
                        new
                        {
                            TypeId = 19,
                            AuctionCategoryId = 2,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Cita manta"
                        },
                        new
                        {
                            TypeId = 20,
                            AuctionCategoryId = 3,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Dzīvoklis"
                        },
                        new
                        {
                            TypeId = 21,
                            AuctionCategoryId = 3,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Māja"
                        },
                        new
                        {
                            TypeId = 22,
                            AuctionCategoryId = 3,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Zeme"
                        },
                        new
                        {
                            TypeId = 23,
                            AuctionCategoryId = 3,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Telpa"
                        },
                        new
                        {
                            TypeId = 24,
                            AuctionCategoryId = 3,
                            CreatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Deleted = false,
                            LastUpdatedAt = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 1,
                            Name = "Garāža"
                        });
                });

            modelBuilder.Entity("Bidding.Database.DatabaseModels.Auctions.Auction", b =>
                {
                    b.HasOne("Bidding.Models.DatabaseModels.Category", "Category")
                        .WithMany("Auctions")
                        .HasForeignKey("AuctionCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bidding.Database.DatabaseModels.Auctions.AuctionFormat", "AuctionFormat")
                        .WithMany()
                        .HasForeignKey("AuctionFormatId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bidding.Database.DatabaseModels.Auctions.AuctionStatus", "AuctionStatus")
                        .WithMany("Auctions")
                        .HasForeignKey("AuctionStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bidding.Models.DatabaseModels.Type", "Type")
                        .WithMany("Auctions")
                        .HasForeignKey("AuctionTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bidding.Database.DatabaseModels.Users.User", "User")
                        .WithMany("Auctions")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Bidding.Database.DatabaseModels.Auctions.AuctionCondition", b =>
                {
                    b.HasOne("Bidding.Database.DatabaseModels.Users.User", "User")
                        .WithMany("AuctionConditions")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Bidding.Database.DatabaseModels.Auctions.AuctionCreator", b =>
                {
                    b.HasOne("Bidding.Database.DatabaseModels.Users.User", "User")
                        .WithMany("AuctionCreators")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Bidding.Database.DatabaseModels.Auctions.AuctionDetails", b =>
                {
                    b.HasOne("Bidding.Database.DatabaseModels.Auctions.AuctionItem", "AuctionItem")
                        .WithMany()
                        .HasForeignKey("AuctionItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bidding.Database.DatabaseModels.Item.ItemCondition", "ItemCondition")
                        .WithMany("AuctionDetails")
                        .HasForeignKey("ConditionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bidding.Database.DatabaseModels.Vehicle.VehicleFuelType", "VehicleFuelType")
                        .WithMany("AuctionDetails")
                        .HasForeignKey("FuelTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bidding.Database.DatabaseModels.Vehicle.VehicleTransmission", "VehicleTransmission")
                        .WithMany("AuctionDetails")
                        .HasForeignKey("TransmissionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bidding.Database.DatabaseModels.Users.User", "User")
                        .WithMany("AuctionDetails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Bidding.Database.DatabaseModels.Auctions.AuctionFormat", b =>
                {
                    b.HasOne("Bidding.Database.DatabaseModels.Users.User", "User")
                        .WithMany("AuctionFormats")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Bidding.Database.DatabaseModels.Auctions.AuctionItem", b =>
                {
                    b.HasOne("Bidding.Database.DatabaseModels.Auctions.Auction", "Auction")
                        .WithMany("AuctionItems")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bidding.Models.DatabaseModels.Category", "Category")
                        .WithMany("AuctionItems")
                        .HasForeignKey("AuctionItemCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bidding.Models.DatabaseModels.Type", "Type")
                        .WithMany("AuctionItems")
                        .HasForeignKey("AuctionItemTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bidding.Database.DatabaseModels.Users.User", "User")
                        .WithMany("AuctionItems")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Bidding.Database.DatabaseModels.Auctions.AuctionStatus", b =>
                {
                    b.HasOne("Bidding.Database.DatabaseModels.Users.User", "User")
                        .WithMany("AuctionStatuses")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Bidding.Database.DatabaseModels.Item.ItemCondition", b =>
                {
                    b.HasOne("Bidding.Database.DatabaseModels.Users.User", "User")
                        .WithMany("ItemConditions")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Bidding.Database.DatabaseModels.Users.Role", b =>
                {
                    b.HasOne("Bidding.Database.DatabaseModels.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Bidding.Database.DatabaseModels.Users.User", b =>
                {
                    b.HasOne("Bidding.Database.DatabaseModels.Users.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Bidding.Database.DatabaseModels.Vehicle.VehicleFuelType", b =>
                {
                    b.HasOne("Bidding.Database.DatabaseModels.Users.User", "User")
                        .WithMany("VehicleFuelTypes")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Bidding.Database.DatabaseModels.Vehicle.VehicleTransmission", b =>
                {
                    b.HasOne("Bidding.Database.DatabaseModels.Users.User", "User")
                        .WithMany("VehicleTransmissions")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Bidding.Models.DatabaseModels.Category", b =>
                {
                    b.HasOne("Bidding.Database.DatabaseModels.Users.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Bidding.Models.DatabaseModels.Type", b =>
                {
                    b.HasOne("Bidding.Models.DatabaseModels.Category", "Category")
                        .WithMany("Types")
                        .HasForeignKey("AuctionCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bidding.Database.DatabaseModels.Users.User", "User")
                        .WithMany("Types")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
