export class RegionsConstants {
  static names = [
    { id: 1, name: "Daugavpils" },
    { id: 2, name: "Jēkabpils" },
    { id: 3, name: "Jelgava" },
    { id: 4, name: "Jūrmala" },
    { id: 5, name: "Liepāja" },
    { id: 6, name: "Rēzekne" },
    { id: 7, name: "Rīga" },
    { id: 8, name: "Valmiera" },
    { id: 9, name: "Ventspils" },
    { id: 10, name: "Ādažu novads" },
    { id: 11, name: "Aglonas novads" },
    { id: 12, name: "Aizkraukles novads" },
    { id: 13, name: "Aizputes novads" },
    { id: 14, name: "Aknīstes novads" },
    { id: 15, name: "Alojas novads" },
    { id: 16, name: "Alsungas novads" },
    { id: 17, name: "Alūksnes novads" },
    { id: 18, name: "Amatas novads" },
    { id: 19, name: "Apes novads" },
    { id: 20, name: "Auces novads" },
    { id: 21, name: "Babītes novads" },
    { id: 22, name: "Baldones novads" },
    { id: 23, name: "Baltinavas novads" },
    { id: 24, name: "Balvu novads" },
    { id: 25, name: "Bauskas novads" },
    { id: 26, name: "Beverīnas novads" },
    { id: 27, name: "Brocēnu novads" },
    { id: 28, name: "Burtnieku novads" },
    { id: 29, name: "Carnikavas novads" },
    { id: 30, name: "Cēsu novads " },
    { id: 31, name: "Cesvaines novads" },
    { id: 32, name: "Ciblas novads" },
    { id: 33, name: "Dagdas novads" },
    { id: 34, name: "Daugavpils novads" },
    { id: 35, name: "Dobeles novads" },
    { id: 36, name: "Dundagas novads" },
    { id: 37, name: "Durbes novads" },
    { id: 38, name: "Engures novads" },
    { id: 39, name: "Ērgļu novads" },
    { id: 40, name: "Garkalnes novads" },
    { id: 41, name: "Grobiņas novads" },
    { id: 42, name: "Gulbenes novads" },
    { id: 43, name: "Iecavas novads" },
    { id: 44, name: "Ikšķiles novads" },
    { id: 45, name: "Ilūkstes novads" },
    { id: 46, name: "Inčukalna novads" },
    { id: 47, name: "Jaunjelgavas novads" },
    { id: 48, name: "Jaunpiebalgas novads" },
    { id: 49, name: "Jaunpils novads" },
    { id: 50, name: "Jēkabpils novads" },
    { id: 51, name: "Jelgavas novads" },
    { id: 52, name: "Kandavas novads" },
    { id: 53, name: "Kārsavas novads" },
    { id: 54, name: "Ķeguma novads" },
    { id: 55, name: "Ķekavas novads" },
    { id: 56, name: "Kocēnu novads" },
    { id: 57, name: "Kokneses novads" },
    { id: 58, name: "Krāslavas novads" },
    { id: 59, name: "Krimuldas novads" },
    { id: 60, name: "Krustpils novads" },
    { id: 61, name: "Kuldīgas novads" },
    { id: 62, name: "Lielvārdes novads" },
    { id: 63, name: "Līgatnes novads" },
    { id: 64, name: "Limbažu novads" },
    { id: 65, name: "Līvānu novads" },
    { id: 66, name: "Lubānas novads" },
    { id: 67, name: "Ludzas novads" },
    { id: 68, name: "Madonas novads" },
    { id: 69, name: "Mālpils novads" },
    { id: 70, name: "Mazsalacas novads" },
    { id: 71, name: "Mērsraga novads" },
    { id: 72, name: "Naukšēnu novads" },
    { id: 73, name: "Neretas novads" },
    { id: 74, name: "Nīcas novads" },
    { id: 75, name: "Ogres novads" },
    { id: 76, name: "Olaines novads" },
    { id: 77, name: "Ozolnieku novads" },
    { id: 78, name: "Pārgaujas novads" },
    { id: 79, name: "Pāvilostas novads" },
    { id: 80, name: "Pļaviņu novads" },
    { id: 81, name: "Preiļu novads" },
    { id: 82, name: "Priekules novads" },
    { id: 83, name: "Priekuļu novads" },
    { id: 84, name: "Raunas novads" },
    { id: 85, name: "Rēzeknes novads" },
    { id: 86, name: "Riebiņu novads" },
    { id: 87, name: "Rojas novads" },
    { id: 88, name: "Ropažu novads" },
    { id: 89, name: "Rucavas novads" },
    { id: 90, name: "Rugāju novads" },
    { id: 91, name: "Rūjienas novads" },
    { id: 92, name: "Rundāles novads" },
    { id: 93, name: "Salacgrīvas novads" },
    { id: 94, name: "Salas novads" },
    { id: 95, name: "Salaspils novads" },
    { id: 96, name: "Saldus novads" },
    { id: 97, name: "Saulkrastu novads" },
    { id: 98, name: "Sējas novads" },
    { id: 99, name: "Siguldas novads" },
    { id: 100, name: "Skrīveru novads" },
    { id: 101, name: "Skrundas novads" },
    { id: 102, name: "Smiltenes novads" },
    { id: 103, name: "Stopiņu novads" },
    { id: 104, name: "Strenču novads" },
    { id: 105, name: "Talsu novads" },
    { id: 106, name: "Tērvetes novads" },
    { id: 107, name: "Tukuma novads" },
    { id: 108, name: "Vaiņodes novads" },
    { id: 109, name: "Valkas novads" },
    { id: 110, name: "Varakļānu novads" },
    { id: 111, name: "Vārkavas novads" },
    { id: 112, name: "Vecpiebalgas novads" },
    { id: 113, name: "Vecumnieku novads " },
    { id: 114, name: "Ventspils novads" },
    { id: 115, name: "Viesītes novads" },
    { id: 116, name: "Viļakas novads" },
    { id: 117, name: "Viļānu novads" },
    { id: 118, name: "Zilupes novads" }
  ];
}
