using System.Collections.Generic;

namespace Bidding.Shared.Constants
{
    public static class Regions
    {
        public static readonly Dictionary<int, string> Names = new Dictionary<int, string>
        {
            {  1,  "Daugavpils" },
            {  2,  "Jēkabpils" },
            {  3,  "Jelgava" },
            {  4,  "Jūrmala" },
            {  5,  "Liepāja" },
            {  6,  "Rēzekne" },
            {  7,  "Rīga" },
            {  8,  "Valmiera" },
            {  9,  "Ventspils" },
            {  10,  "Ādažu novads" },
            {  11,  "Aglonas novads" },
            {  12,  "Aizkraukles novads" },
            {  13,  "Aizputes novads" },
            {  14,  "Aknīstes novads" },
            {  15,  "Alojas novads" },
            {  16,  "Alsungas novads" },
            {  17,  "Alūksnes novads" },
            {  18,  "Amatas novads" },
            {  19,  "Apes novads" },
            {  20,  "Auces novads" },
            {  21,  "Babītes novads" },
            {  22,  "Baldones novads" },
            {  23,  "Baltinavas novads" },
            {  24,  "Balvu novads" },
            {  25,  "Bauskas novads" },
            {  26,  "Beverīnas novads" },
            {  27,  "Brocēnu novads" },
            {  28,  "Burtnieku novads" },
            {  29,  "Carnikavas novads" },
            {  30,  "Cēsu novads " },
            {  31,  "Cesvaines novads" },
            {  32,  "Ciblas novads" },
            {  33,  "Dagdas novads" },
            {  34,  "Daugavpils novads" },
            {  35,  "Dobeles novads" },
            {  36,  "Dundagas novads" },
            {  37,  "Durbes novads" },
            {  38,  "Engures novads" },
            {  39,  "Ērgļu novads" },
            {  40,  "Garkalnes novads" },
            {  41,  "Grobiņas novads" },
            {  42,  "Gulbenes novads" },
            {  43,  "Iecavas novads" },
            {  44,  "Ikšķiles novads" },
            {  45,  "Ilūkstes novads" },
            {  46,  "Inčukalna novads" },
            {  47,  "Jaunjelgavas novads" },
            {  48,  "Jaunpiebalgas novads" },
            {  49,  "Jaunpils novads" },
            {  50,  "Jēkabpils novads" },
            {  51,  "Jelgavas novads" },
            {  52,  "Kandavas novads" },
            {  53,  "Kārsavas novads" },
            {  54,  "Ķeguma novads" },
            {  55,  "Ķekavas novads" },
            {  56,  "Kocēnu novads" },
            {  57,  "Kokneses novads" },
            {  58,  "Krāslavas novads" },
            {  59,  "Krimuldas novads" },
            {  60,  "Krustpils novads" },
            {  61,  "Kuldīgas novads" },
            {  62,  "Lielvārdes novads" },
            {  63,  "Līgatnes novads" },
            {  64,  "Limbažu novads" },
            {  65,  "Līvānu novads" },
            {  66,  "Lubānas novads" },
            {  67,  "Ludzas novads" },
            {  68,  "Madonas novads" },
            {  69,  "Mālpils novads" },
            {  70,  "Mazsalacas novads" },
            {  71,  "Mērsraga novads" },
            {  72,  "Naukšēnu novads" },
            {  73,  "Neretas novads" },
            {  74,  "Nīcas novads" },
            {  75,  "Ogres novads" },
            {  76,  "Olaines novads" },
            {  77,  "Ozolnieku novads" },
            {  78,  "Pārgaujas novads" },
            {  79,  "Pāvilostas novads" },
            {  80,  "Pļaviņu novads" },
            {  81,  "Preiļu novads" },
            {  82,  "Priekules novads" },
            {  83,  "Priekuļu novads" },
            {  84,  "Raunas novads" },
            {  85,  "Rēzeknes novads" },
            {  86,  "Riebiņu novads" },
            {  87,  "Rojas novads" },
            {  88,  "Ropažu novads" },
            {  89,  "Rucavas novads" },
            {  90,  "Rugāju novads" },
            {  91,  "Rūjienas novads" },
            {  92,  "Rundāles novads" },
            {  93,  "Salacgrīvas novads" },
            {  94,  "Salas novads" },
            {  95,  "Salaspils novads" },
            {  96,  "Saldus novads" },
            {  97,  "Saulkrastu novads" },
            {  98,  "Sējas novads" },
            {  99,  "Siguldas novads" },
            {  100,  "Skrīveru novads" },
            {  101,  "Skrundas novads" },
            {  102,  "Smiltenes novads" },
            {  103,  "Stopiņu novads" },
            {  104,  "Strenču novads" },
            {  105,  "Talsu novads" },
            {  106,  "Tērvetes novads" },
            {  107,  "Tukuma novads" },
            {  108,  "Vaiņodes novads" },
            {  109,  "Valkas novads" },
            {  110,  "Varakļānu novads" },
            {  111,  "Vārkavas novads" },
            {  112,  "Vecpiebalgas novads" },
            {  113,  "Vecumnieku novads " },
            {  114,  "Ventspils novads" },
            {  115,  "Viesītes novads" },
            {  116,  "Viļakas novads" },
            {  117,  "Viļānu novads" },
            {  118,  "Zilupes novads" }
        };
    }
}
